# Never copy this from other mod, always use https://github.com/ALIENQuake/ProjectInfinity/wiki/Adding-metadata-for-mod
# Filename must be the same as tp2 basename, placed at the same folder where
# .tp2 file is located, use UTF8 (without BOM) encoding, everything is optional

# ini section header is required to avoid false detection
[Metadata]

# Full name of the mod, without version number
Name = Shar-Teel SoD

# Author name or nick, don't use email address
Author = elminster

# Short description of the mod, main goals, features etc
Description = Playable Shar-Teel NPC for Siege of Dragonspear

# Web address of mod readme file (filename is case-sensitive!), comma-separated list. You can link to txt, md, html, pdf etc.
# Readme =

# Web address of mod dedicated forum or forum thread 
Forum = https://forums.beamdog.com/discussion/62941/no-longer-supported-shar-teel-npc-mod-sod/

# Web address of mod Homepage
Homepage = https://github.com/panshaigan/Shar-Teel-SoD

# if you use Github.com (preferred hosting site), simply use github.com/AccountOrOrgName/RepositoryName    
# If you use other hosting sites, please check requirements and put direct download link  
Download = https://github.com/panshaigan/Shar-Teel-SoD

# Type of LABELs used by the mod, read more here https://www.gibberlings3.net/forums/topic/32516-tutorial-what-is-label
LabelType = GloballyUnique

# Dynamic Install Order, use mod ID as tp2 name without file extension and `setup-` prefix

# This mod must be installed *before* those ModID listed below, comma-separated list:
Before = EET

# This mod must be installed *after* those ModID listed below, comma-separated list:
# After = EET, ModY